(function(){
'use strict';
const VIEW = window.__QUIZ_VIEW__ || 'public';
const STORAGE_KEY = 'eu-flags-quiz-github-ready-fixed';
const CHANNEL_NAME = 'eu-flags-quiz-github-ready-fixed';
const ROUND_MS = 3000;
const KEY_A = 'enter';
const KEY_B = 'l';
const C = { blue:'#004494', deep:'#071A3D', soft:'#163B7A', yellow:'#FFCC00', white:'#FFFFFF', panel:'rgba(8,18,44,0.92)', line:'rgba(255,255,255,0.10)', green:'#16A34A', red:'#DC2626' };
const FLAGS = [
 ['Belgique','be','🇧🇪'],['Bulgarie','bg','🇧🇬'],['Tchéquie','cz','🇨🇿'],['Danemark','dk','🇩🇰'],['Allemagne','de','🇩🇪'],['Estonie','ee','🇪🇪'],['Irlande','ie','🇮🇪'],['Grèce','gr','🇬🇷'],['Espagne','es','🇪🇸'],['France','fr','🇫🇷'],['Croatie','hr','🇭🇷'],['Italie','it','🇮🇹'],['Chypre','cy','🇨🇾'],['Lettonie','lv','🇱🇻'],['Lituanie','lt','🇱🇹'],['Luxembourg','lu','🇱🇺'],['Hongrie','hu','🇭🇺'],['Malte','mt','🇲🇹'],['Pays-Bas','nl','🇳🇱'],['Autriche','at','🇦🇹'],['Pologne','pl','🇵🇱'],['Portugal','pt','🇵🇹'],['Roumanie','ro','🇷🇴'],['Slovénie','si','🇸🇮'],['Slovaquie','sk','🇸🇰'],['Finlande','fi','🇫🇮'],['Suède','se','🇸🇪']
].map(x=>({country:x[0], code:x[1], emoji:x[2], svg:'https://flagcdn.io/flags/4x3/'+x[1]+'.svg'}));
let isFullscreen = false;
let useSvg = true;
let bc = null;
let flashTimer = null;
let audioCtx = null;
function shuffle(arr){ const c=arr.slice(); for(let i=c.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [c[i],c[j]]=[c[j],c[i]]; } return c; }
function esc(s){ return String(s).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
function fmt(ms){ return ms==null ? '—' : (ms/1000).toFixed(3)+' s'; }
function initialState(){ return { deck: shuffle(FLAGS).map(f=>f.code), index:0, phase:'ready', roundStart:null, winnerPlayer:null, winnerTime:null, loserPlayer:null, loserTime:null, scoreA:0, scoreB:0, bestA:null, bestB:null, officialWinner:null, officialLoser:null, showAnswer:false, judged:false, status:'Prêt pour lancer la manche.', judgeText:'', lastUpdatedAt:Date.now() }; }
function loadState(){ try { return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null') || initialState(); } catch(e){ return initialState(); } }
let state = loadState();
function saveState(){ try{ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }catch(e){} try{ if(bc) bc.postMessage(state); }catch(e){} }
function commit(updater){ const nextBase = typeof updater === 'function' ? updater(state) : updater; state = Object.assign({}, nextBase, { lastUpdatedAt: Date.now() }); saveState(); render(); }
function currentFlag(){ return FLAGS.find(f=>f.code===state.deck[state.index]) || FLAGS[0]; }
function sideStatus(player){ if(state.officialWinner===player) return {border:C.green,bg:'rgba(22,163,74,0.16)',buzz:C.green,text:C.green}; if(state.officialLoser===player) return {border:C.red,bg:'rgba(220,38,38,0.14)',buzz:C.red,text:C.red}; if(state.winnerPlayer===player && !state.judged) return {border:C.yellow,bg:'rgba(255,204,0,0.10)',buzz:C.yellow,text:C.yellow}; return {border:C.line,bg:C.panel,buzz:player==='A'?C.yellow:C.blue,text:player==='A'?C.yellow:C.blue}; }
function playBuzz(player){ try{ const AC = window.AudioContext || window.webkitAudioContext; if(!AC) return; if(!audioCtx) audioCtx = new AC(); if(audioCtx.state==='suspended') audioCtx.resume(); const now=audioCtx.currentTime; const o1=audioCtx.createOscillator(), o2=audioCtx.createOscillator(), g=audioCtx.createGain(); if(player==='A'){ o1.type='square'; o2.type='triangle'; o1.frequency.setValueAtTime(880,now); o2.frequency.setValueAtTime(1320,now+0.015);} else { o1.type='sawtooth'; o2.type='square'; o1.frequency.setValueAtTime(600,now); o2.frequency.setValueAtTime(480,now+0.02);} g.gain.setValueAtTime(0.0001,now); g.gain.exponentialRampToValueAtTime(0.30,now+0.015); g.gain.exponentialRampToValueAtTime(0.0001,now+0.30); o1.connect(g); o2.connect(g); g.connect(audioCtx.destination); o1.start(now); o2.start(now); o1.stop(now+0.30); o2.stop(now+0.30);}catch(e){} }
function flash(colour){ const el=document.getElementById('flash'); if(!el) return; el.style.display='block'; el.style.background=colour; clearTimeout(flashTimer); flashTimer=setTimeout(()=>{el.style.display='none';},320); }
function startRound(){ commit(prev=>{ const adv=prev.phase==='ended' || prev.phase==='locked'; const nextIndex = adv ? ((prev.index+1)%prev.deck.length) : prev.index; const nextDeck = adv && nextIndex===0 ? shuffle(FLAGS).map(f=>f.code) : prev.deck; return { deck:nextDeck,index:nextIndex,phase:'live',roundStart:Date.now(),winnerPlayer:null,winnerTime:null,loserPlayer:null,loserTime:null,scoreA:prev.scoreA,scoreB:prev.scoreB,bestA:prev.bestA,bestB:prev.bestB,officialWinner:null,officialLoser:null,showAnswer:false,judged:false,status:'Buzz ouverts immédiatement.',judgeText:'' }; }); }
function resetAll(){ commit(initialState()); }
function registerPress(player){ if(VIEW!=='public') return; if(!state.roundStart) return; if(state.phase!=='live' && state.phase!=='locked') return; const reaction=Math.min(Date.now()-state.roundStart, ROUND_MS); if(!state.winnerPlayer && state.phase==='live'){ flash(player==='A'?'rgba(255,204,0,0.26)':'rgba(0,68,148,0.28)'); playBuzz(player); commit(prev=>({ deck:prev.deck,index:prev.index,phase:'locked',roundStart:prev.roundStart,winnerPlayer:player,winnerTime:reaction,loserPlayer:null,loserTime:null,scoreA:prev.scoreA,scoreB:prev.scoreB,bestA:player==='A'?(prev.bestA==null||reaction<prev.bestA?reaction:prev.bestA):prev.bestA,bestB:player==='B'?(prev.bestB==null||reaction<prev.bestB?reaction:prev.bestB):prev.bestB,officialWinner:null,officialLoser:null,showAnswer:prev.showAnswer,judged:false,status:'Premier buzz : Candidat '+player,judgeText:'' })); return; } if(state.phase==='locked' && state.winnerPlayer && player!==state.winnerPlayer && !state.loserPlayer){ commit(prev=>Object.assign({}, prev, {loserPlayer:player, loserTime:reaction, status:'Duel enregistré : Candidat '+prev.winnerPlayer+' devant Candidat '+player})); } }
function designate(code){ if(VIEW!=='animateur') return; if(['A','B','none'].indexOf(code)===-1) return; commit(prev=>Object.assign({}, prev, { phase:'ended', winnerPlayer: code==='none'?prev.winnerPlayer:code, scoreA: code==='A'?prev.scoreA+1:prev.scoreA, scoreB: code==='B'?prev.scoreB+1:prev.scoreB, officialWinner: code==='none'?null:code, officialLoser: code==='none'?null:(code==='A'?'B':'A'), judged:true, status: code==='none'?'Aucun gagnant désigné.':'Gagnant officiel : Candidat '+code, judgeText: code==='none'?'La manche est clôturée sans gagnant.':'Point attribué au Candidat '+code+'.' })); }
function toggleAnswer(){ if(VIEW!=='animateur') return; commit(prev=>Object.assign({}, prev, {showAnswer:!prev.showAnswer})); }
function toggleFullscreen(){ if(!document.fullscreenElement){ document.documentElement.requestFullscreen().catch(()=>{}); } else { document.exitFullscreen().catch(()=>{});} }
function metricCard(t,v,border,text){ return '<div class="metric" style="border-color:'+border+'"><div class="metric-t"'+(text?' style="color:'+text+'"':'')+'>'+esc(t)+'</div><div class="metric-v"'+(text?' style="color:'+text+'"':'')+'>'+esc(v)+'</div></div>'; }
function sideHtml(player, styleObj, buzzEnabled){ const score=player==='A'?state.scoreA:state.scoreB; const best=player==='A'?state.bestA:state.bestB; const time=state.winnerPlayer===player?state.winnerTime:(state.loserPlayer===player?state.loserTime:null); const keyLabel=player==='A'?'Enter / USB':'Touche L'; return '<aside class="side" style="background:'+styleObj.bg+';border-color:'+styleObj.border+'"><div class="side-top"><div class="side-label">Candidat '+player+'</div><div class="key" style="border-color:'+styleObj.border+'">'+keyLabel+'</div></div><button id="buzz-'+player+'" '+(buzzEnabled?'':'disabled')+' class="buzz" style="border-color:'+(buzzEnabled?styleObj.buzz:C.line)+';background:'+(buzzEnabled?styleObj.buzz:'rgba(15,23,42,0.45)')+';opacity:'+(VIEW==='animateur'?'0.38':'1')+';box-shadow:'+((state.winnerPlayer===player&&!state.judged)?('0 0 90px '+styleObj.buzz):'none')+'">BUZZ</button><div class="stack">'+metricCard('Temps manche',fmt(time),styleObj.border)+metricCard('Record',fmt(best),styleObj.border)+metricCard('Score',String(score),styleObj.border,styleObj.text)+'</div></aside>'; }
function render(){ const root=document.getElementById('root'); const flag=currentFlag(); const elapsed=state.roundStart && (state.phase==='live'||state.phase==='locked') ? Math.min(Date.now()-state.roundStart, ROUND_MS) : (state.winnerTime || 0); const left=Math.max(0, ROUND_MS-elapsed); const countdown=(left/1000).toFixed(2); const ringRadius=160; const ringCirc=2*Math.PI*ringRadius; const dashOffset=ringCirc*(1-Math.max(0,Math.min(100,(left/ROUND_MS)*100))/100); const winnerName=state.winnerPlayer?'Candidat '+state.winnerPlayer:'—'; const duelDelta=state.winnerTime!=null && state.loserTime!=null ? ((state.loserTime-state.winnerTime)/1000).toFixed(3)+' s' : '—'; const sa=sideStatus('A'); const sb=sideStatus('B'); const buzzEnabled=VIEW==='public' && (state.phase==='live'||state.phase==='locked');
root.innerHTML = '<div id="flash" class="flash"></div>'+
(state.winnerPlayer && !state.judged ? '<div class="banner-wrap"><div class="banner" style="border-color:'+(state.winnerPlayer==='A'?C.yellow:C.blue)+';background:'+(state.winnerPlayer==='A'?C.yellow:C.blue)+';color:'+(state.winnerPlayer==='A'?C.deep:C.white)+'">PREMIER BUZZ — CANDIDAT '+esc(state.winnerPlayer)+'</div></div>' : '')+
'<div class="shell"><div class="wrap"><header class="header"><div class="brand"><div class="brand-mark">COMITÉ EUROPÉEN DES RÉGIONS</div><div><div class="kicker">'+(VIEW==='animateur'?'Vue animateur':'Vue publique')+'</div><h1>European Committee of the Regions — EU Flags Challenge</h1><div class="sub">'+(VIEW==='public'?'Affichage public et buzz candidats':'Pilotage animateur et validation officielle')+'</div></div></div><div class="controls">'+
(VIEW==='animateur' ? '<button id="start-btn" class="btn primary">'+(state.phase==='live'?'Manche en cours':(state.phase==='ready'?'Démarrer le quiz':'Démarrer la manche suivante'))+'</button><button id="reset-btn" class="btn dark">Réinitialiser</button>' : '')+
'<button id="fs-btn" class="btn secondary">'+(isFullscreen?'Quitter plein écran':'Plein écran')+'</button><button id="mode-btn" class="btn secondary">'+(useSvg?'Mode emoji':'Mode SVG')+'</button>'+
(VIEW==='public' ? '<a class="btn link accent" href="animateur/">Vue animateur</a>' : '<a class="btn link" href="../">Vue publique</a>')+
'</div></header><main class="grid">'+
sideHtml('A',sa,buzzEnabled)+
'<section class="centre"><div class="centre-grid" style="grid-template-columns:'+(VIEW==='animateur'?'1.62fr .95fr':'1fr')+'"><section class="quiz"><div class="panel-kicker">Drapeau à deviner</div><div class="stage"><div class="ring-wrap"><svg class="ring" viewBox="0 0 400 400"><circle cx="200" cy="200" r="'+ringRadius+'" stroke="rgba(255,255,255,0.08)" stroke-width="18" fill="none"></circle><circle cx="200" cy="200" r="'+ringRadius+'" stroke="'+C.yellow+'" stroke-width="18" fill="none" stroke-linecap="round" stroke-dasharray="'+ringCirc+' '+ringCirc+'" stroke-dashoffset="'+dashOffset+'"></circle></svg><div class="flag-content">'+(useSvg?'<div class="flag-card"><img src="'+esc(flag.svg)+'" alt="Drapeau" class="flag-img" onerror="window.__quizFallbackEmoji()"></div>':'<div class="emoji">'+esc(flag.emoji)+'</div>')+'</div></div><div class="count">'+countdown+'</div>'+(VIEW==='animateur'?'<div class="question">Question '+(state.index+1)+' / '+state.deck.length+'</div>':'')+'</div><div class="info-grid">'+metricCard('Gagnant officiel',winnerName,C.line)+metricCard('Temps gagnant',fmt(state.winnerTime),C.line)+metricCard('Écart duel',duelDelta,C.line)+'</div></section>'+
(VIEW==='animateur' ? '<section class="anim"><div class="anim-card"><div class="anim-title">Bonne réponse</div><div class="answer"><span>'+(state.showAnswer?esc(flag.country):'********')+'</span></div><button id="reveal-btn" class="btn secondary wide">'+(state.showAnswer?'Masquer la bonne réponse':'Voir la bonne réponse')+'</button></div><div class="anim-card"><div class="anim-title">Désigner le gagnant</div><div class="actions"><button id="win-a" class="btn win">Valider candidat A gagnant</button><button id="win-b" class="btn win">Valider candidat B gagnant</button><button id="win-none" class="btn secondary">Aucun gagnant</button></div><div class="status">'+esc(state.status)+'</div><div class="note">'+esc(state.judgeText||'L’écran animateur pilote officiellement la manche.')+'</div></div></section>' : '')+
'</div></section>'+sideHtml('B',sb,buzzEnabled)+'</main></div></div>';
const bind=(id,fn)=>{ const el=document.getElementById(id); if(el) el.onclick=fn; };
bind('start-btn',startRound); bind('reset-btn',resetAll); bind('fs-btn',toggleFullscreen); bind('mode-btn',()=>{useSvg=!useSvg; render();}); bind('buzz-A',()=>registerPress('A')); bind('buzz-B',()=>registerPress('B')); bind('reveal-btn',toggleAnswer); bind('win-a',()=>designate('A')); bind('win-b',()=>designate('B')); bind('win-none',()=>designate('none')); }
try { bc = new BroadcastChannel(CHANNEL_NAME); bc.onmessage = function(e){ if(e && e.data && (e.data.lastUpdatedAt||0)>(state.lastUpdatedAt||0)){ state=e.data; render(); } }; } catch(e) { bc = null; }
window.addEventListener('storage', function(e){ if(e.key!==STORAGE_KEY || !e.newValue) return; try{ const parsed = JSON.parse(e.newValue); if(parsed && (parsed.lastUpdatedAt||0)>(state.lastUpdatedAt||0)){ state=parsed; render(); } } catch(err){} });
document.addEventListener('fullscreenchange', function(){ isFullscreen = !!document.fullscreenElement; render(); });
window.__quizFallbackEmoji = function(){ useSvg=false; render(); };
window.addEventListener('keydown', function(e){ const key=String(e.key||'').toLowerCase(); if(e.repeat) return; if(VIEW==='public' && (state.phase==='live'||state.phase==='locked') && key===KEY_A){ e.preventDefault(); registerPress('A'); return; } if(VIEW==='public' && (state.phase==='live'||state.phase==='locked') && key===KEY_B){ e.preventDefault(); registerPress('B'); return; } if(key==='f'){ e.preventDefault(); toggleFullscreen(); return; } if(VIEW==='animateur' && key===' '){ e.preventDefault(); startRound(); }});
setInterval(function(){ if(state.roundStart && (state.phase==='live'||state.phase==='locked')) render(); }, 60);
render();
})();